// 临时脚本：为 iisaacbeats.cn 生成 API 服务端文件
// 用法：node _gen_api_files.js
const fs = require('fs');
const path = require('path');

const API_DIR = 'I:/iisaacbeats.cn/api';

// ==================== package.json ====================
const packageJson = JSON.stringify({
  "name": "iisaacbeats-api",
  "version": "1.0.0",
  "private": true,
  "description": "iisaacbeats.cn API server — telemetry & update check",
  "scripts": {
    "start": "node server.js",
    "init-db": "node init_db.js"
  },
  "dependencies": {
    "better-sqlite3": "^11.0.0"
  }
}, null, 2);

// ==================== server.js ====================
const serverJs = [
  '// ==========================================================',
  '// iisaacbeats.cn/api/server.js',
  '//   Node.js HTTP API —— 遥测接收 + 更新检查',
  '//',
  '// 部署：',
  '//   1. cd api && npm install    （安装依赖）',
  '//   2. node init_db.js         （初始化数据库，仅首次）',
  '//   3. node server.js          （启动服务，监听 127.0.0.1:3001）',
  '//   4. Nginx 配置反向代理 location /api/ { proxy_pass http://127.0.0.1:3001; }',
  '//   5. pm2 start server.js --name y2k-api  （守护进程）',
  '//',
  '// API 端点：',
  '//   POST /api/telemetry/ping  — 遥测心跳',
  '//   GET  /api/update/check    — 版本更新检查',
  '// ==========================================================',
  '',
  'const http = require("http");',
  'const Database = require("better-sqlite3");',
  'const path = require("path");',
  '',
  'const PORT = parseInt(process.env.PORT || "3001", 10);',
  'const HOST = process.env.HOST || "127.0.0.1";',
  'const DB_PATH = path.join(__dirname, "data.db");',
  '',
  '// ---- 初始化数据库 ----',
  'const db = new Database(DB_PATH);',
  'db.pragma("journal_mode = WAL");',
  'db.pragma("foreign_keys = ON");',
  '',
  'db.exec(`',
  '  CREATE TABLE IF NOT EXISTS telemetry (',
  '    id                 INTEGER PRIMARY KEY AUTOINCREMENT,',
  '    client_id          TEXT    NOT NULL,',
  '    version            TEXT    NOT NULL DEFAULT "",',
  '    build_type         TEXT    NOT NULL DEFAULT "",',
  '    platform           TEXT    NOT NULL DEFAULT "",',
  '    os                 TEXT    NOT NULL DEFAULT "",',
  '    cpu_vendor         TEXT    NOT NULL DEFAULT "",',
  '    cpu_model          TEXT    NOT NULL DEFAULT "",',
  '    cpu_cores          INTEGER NOT NULL DEFAULT 0,',
  '    ram_mb             INTEGER NOT NULL DEFAULT 0,',
  '    plugin_mode        TEXT    NOT NULL DEFAULT "",',
  '    host_name          TEXT    NOT NULL DEFAULT "",',
  '    display_count      INTEGER NOT NULL DEFAULT 0,',
  '    primary_display_w  INTEGER NOT NULL DEFAULT 0,',
  '    primary_display_h  INTEGER NOT NULL DEFAULT 0,',
  '    source_tag         TEXT    NOT NULL DEFAULT "",',
  '    system_locale      TEXT    NOT NULL DEFAULT "",',
  '    timezone_offset_min INTEGER NOT NULL DEFAULT 0,',
  '    created_at         TEXT    NOT NULL DEFAULT (datetime("now"))',
  '  );',
  '  CREATE INDEX IF NOT EXISTS idx_telemetry_date ON telemetry(created_at);',
  '  CREATE INDEX IF NOT EXISTS idx_telemetry_client_date ON telemetry(client_id, created_at);',
  '',
  '  CREATE TABLE IF NOT EXISTS releases (',
  '    id           INTEGER PRIMARY KEY AUTOINCREMENT,',
  '    version      TEXT    NOT NULL,',
  '    platform     TEXT    NOT NULL DEFAULT "all",',
  '    download_url TEXT    NOT NULL DEFAULT "",',
  '    changelog    TEXT    NOT NULL DEFAULT "",',
  '    force_update INTEGER NOT NULL DEFAULT 0,',
  '    created_at   TEXT    NOT NULL DEFAULT (datetime("now"))',
  '  );',
  '',
  '  INSERT OR IGNORE INTO releases (version, platform, download_url, changelog, force_update)',
  '  VALUES ("2.3.2", "all",',
  '    "https://pan.baidu.com/s/57uOC6W6lH_RHkzJ6x0ds5Q",',
  '    "Telemetry & auto-update initial release.", 0);',
  '`);',
  '',
  'console.log("[server] Database ready:", DB_PATH);',
  '',
  '// ---- 工具函数 ----',
  'function jsonResponse(res, statusCode, data) {',
  '  const headers = {',
  '    "Content-Type": "application/json",',
  '    "Access-Control-Allow-Origin": "*",',
  '    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",',
  '    "Access-Control-Allow-Headers": "Content-Type"',
  '  };',
  '  res.writeHead(statusCode, headers);',
  '  res.end(JSON.stringify(data));',
  '}',
  '',
  'function parseBody(req) {',
  '  return new Promise(function (resolve) {',
  '    var body = "";',
  '    req.on("data", function (chunk) { body += chunk; });',
  '    req.on("end", function () {',
  '      try { resolve(JSON.parse(body)); }',
  '      catch (e) { resolve(null); }',
  '    });',
  '  });',
  '}',
  '',
  'function compareVersions(a, b) {',
  '  var pa = a.split(/[.-]/).map(Number);',
  '  var pb = b.split(/[.-]/).map(Number);',
  '  var len = Math.max(pa.length, pb.length);',
  '  for (var i = 0; i < len; i++) {',
  '    var va = isNaN(pa[i]) ? -1 : (pa[i] || 0);',
  '    var vb = isNaN(pb[i]) ? -1 : (pb[i] || 0);',
  '    if (va > vb) return 1;',
  '    if (va < vb) return -1;',
  '  }',
  '  var suffixA = a.indexOf("-") > 0 ? a.slice(a.indexOf("-")) : "";',
  '  var suffixB = b.indexOf("-") > 0 ? b.slice(b.indexOf("-")) : "";',
  '  if (suffixA && !suffixB) return -1;',
  '  if (!suffixA && suffixB) return 1;',
  '  return 0;',
  '}',
  '',
  'function log(level, msg) {',
  '  console.log("[" + new Date().toISOString() + "] [" + level + "] " + msg);',
  '}',
  '',
  '// ---- 创建 HTTP 服务 ----',
  'var server = http.createServer(function (req, res) {',
  '  var url = new URL(req.url, "http://" + (req.headers.host || "localhost"));',
  '',
  '  if (req.method === "OPTIONS") {',
  '    return jsonResponse(res, 204, null);',
  '  }',
  '',
  '  // ---- POST /api/telemetry/ping ----',
  '  if (url.pathname === "/api/telemetry/ping" && req.method === "POST") {',
  '    parseBody(req).then(function (data) {',
  '      try {',
  '        if (!data || !data.client_id) {',
  '          return jsonResponse(res, 400, { status: "error", message: "Missing client_id" });',
  '        }',
  '',
  '        var today = new Date().toISOString().slice(0, 10);',
  '        var existing = db.prepare(',
  '          "SELECT id FROM telemetry WHERE client_id = ? AND date(created_at) = ? LIMIT 1"',
  '        ).get(data.client_id, today);',
  '',
  '        if (!existing) {',
  '          var stmt = db.prepare(',
  '            "INSERT INTO telemetry (client_id, version, build_type, platform, os, ',
  '             cpu_vendor, cpu_model, cpu_cores, ram_mb, plugin_mode, host_name, ',
  '             display_count, primary_display_w, primary_display_h, source_tag, ',
  '             system_locale, timezone_offset_min, created_at) ',
  '             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"',
  '          );',
  '          stmt.run(',
  '            data.client_id || "",',
  '            data.version || "",',
  '            data.build_type || "",',
  '            data.platform || "",',
  '            data.os || "",',
  '            data.cpu_vendor || "",',
  '            data.cpu_model || "",',
  '            data.cpu_cores || 0,',
  '            data.ram_mb || 0,',
  '            data.plugin_mode || "",',
  '            data.host_name || "",',
  '            data.display_count || 0,',
  '            data.primary_display_w || 0,',
  '            data.primary_display_h || 0,',
  '            data.source_tag || "",',
  '            data.system_locale || "",',
  '            data.timezone_offset_min || 0,',
  '            new Date().toISOString()',
  '          );',
  '          log("INFO", "Telemetry recorded: " + data.client_id + " v" + data.version);',
  '        }',
  '',
  '        jsonResponse(res, 200, { status: "ok" });',
  '      } catch (e) {',
  '        log("ERROR", "Telemetry error: " + e.message);',
  '        jsonResponse(res, 500, { status: "error", message: e.message });',
  '      }',
  '    });',
  '    return;',
  '  }',
  '',
  '  // ---- GET /api/update/check ----',
  '  if (url.pathname === "/api/update/check" && req.method === "GET") {',
  '    try {',
  '      var clientVersion = url.searchParams.get("version") || "0.0.0";',
  '      var clientPlatform = url.searchParams.get("platform") || "unknown";',
  '',
  '      var row = db.prepare(',
  '        "SELECT version, download_url, changelog, force_update FROM releases ',
  '         WHERE platform = ? OR platform = \'all\' ORDER BY created_at DESC LIMIT 1"',
  '      ).get(clientPlatform);',
  '',
  '      if (!row) {',
  '        return jsonResponse(res, 200, { has_update: false });',
  '      }',
  '',
  '      var hasUpdate = compareVersions(row.version, clientVersion) > 0;',
  '',
  '      log("INFO", "Update check: client=" + clientVersion + ',
  '           ", latest=" + row.version + ", update=" + hasUpdate);',
  '',
  '      jsonResponse(res, 200, {',
  '        has_update: hasUpdate,',
  '        latest_version: row.version,',
  '        download_url: row.download_url || "",',
  '        changelog: row.changelog || "",',
  '        force_update: row.force_update === 1',
  '      });',
  '    } catch (e) {',
  '      log("ERROR", "Update check error: " + e.message);',
  '      jsonResponse(res, 200, { has_update: false });',
  '    }',
  '    return;',
  '  }',
  '',
  '  jsonResponse(res, 404, { status: "error", message: "Not found" });',
  '});',
  '',
  'server.listen(PORT, HOST, function () {',
  '  console.log("[server] Y2K API listening on http://" + HOST + ":" + PORT);',
  '  console.log("[server]   POST /api/telemetry/ping");',
  '  console.log("[server]   GET  /api/update/check");',
  '});',
  '',
  'process.on("SIGINT", function () { db.close(); process.exit(0); });',
  'process.on("SIGTERM", function () { db.close(); process.exit(0); });',
  ''
].join('\n');

// ==================== init_db.js ====================
const initDbJs = [
  '// ==========================================================',
  '// iisaacbeats.cn/api/init_db.js',
  '//   SQLite 数据库初始化脚本（服务器端执行一次即可）',
  '//',
  '// 用法：node api/init_db.js',
  '// ==========================================================',
  '',
  'const Database = require("better-sqlite3");',
  'const path = require("path");',
  'const fs = require("fs");',
  '',
  'const DB_PATH = path.join(__dirname, "data.db");',
  'const SCHEMA_PATH = path.join(__dirname, "schema.sql");',
  '',
  'console.log("[init_db] Database path:", DB_PATH);',
  '',
  'const db = new Database(DB_PATH);',
  'db.pragma("journal_mode = WAL");',
  'db.pragma("foreign_keys = ON");',
  '',
  'const schemaSQL = fs.readFileSync(SCHEMA_PATH, "utf-8");',
  'db.exec(schemaSQL);',
  '',
  'console.log("[init_db] Schema executed successfully.");',
  '',
  'const tables = db.prepare(',
  '  "SELECT name FROM sqlite_master WHERE type=\'table\' ORDER BY name"',
  ').all();',
  'console.log("[init_db] Tables:", tables.map(function (t) { return t.name; }).join(", "));',
  '',
  'const releaseCount = db.prepare("SELECT COUNT(*) AS cnt FROM releases").get();',
  'console.log("[init_db] Releases:", releaseCount.cnt);',
  '',
  'db.close();',
  'console.log("[init_db] Done. Database is ready.");',
  ''
].join('\n');

// ---- 写入文件 ----
function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

ensureDir(API_DIR);
fs.writeFileSync(path.join(API_DIR, 'package.json'), packageJson);
fs.writeFileSync(path.join(API_DIR, 'server.js'), serverJs);
fs.writeFileSync(path.join(API_DIR, 'init_db.js'), initDbJs);

console.log('=== All files generated ===');
console.log('  api/package.json');
console.log('  api/server.js');
console.log('  api/init_db.js');
console.log('');
console.log('Next steps on server:');
console.log('  1. cd /path/to/iisaacbeats.cn/api');
console.log('  2. npm install');
console.log('  3. node init_db.js');
console.log('  4. node server.js  (or pm2 start server.js --name y2k-api)');
